PROCESS BEFORE OUTPUT.
  MODULE alimenta_tc.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_CLIENTES'
  MODULE TC_CLIENTES_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_COL_ATTR.
  LOOP AT   IT_Z944620CLI_TC
       INTO WA_Z944620CLI_TC
       WITH CONTROL TC_CLIENTES
       CURSOR TC_CLIENTES-CURRENT_LINE.
    MODULE TC_CLIENTES_GET_LINES.
*&SPWIZARD:   MODULE TC_CLIENTES_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE STATUS_9000.
  MODULE VALIDA_DADOS_9000.
  MODULE CONTROLE_TELA_9000.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_CLIENTES'
  LOOP AT IT_Z944620CLI_TC.
    CHAIN.
      FIELD WA_Z944620CLI_TC-CODCLI.
      FIELD WA_Z944620CLI_TC-NOME.
      FIELD WA_Z944620CLI_TC-TIPOCLI.
      FIELD WA_Z944620CLI_TC-REGIO.
      FIELD WA_Z944620CLI_TC-ATIVO.
    endchain.
  ENDLOOP.
  MODULE TC_CLIENTES_USER_COMMAND.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_9000_EXIT AT EXIT-COMMAND.
  MODULE USER_COMMAND_9000.
